# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [ ]:
# Printing the version of NumPy installed
print(np.__version__)

# Printing the configuration details of NumPy
print(np.show_config())


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [6]:
a = np.random.random(size=(2, 3, 5))


### 4. Print a.


In [7]:
print(a)


[[[0.67092717 0.97148054 0.30944829 0.92458055 0.03261588]
  [0.74698709 0.85811075 0.16735022 0.63663272 0.63236285]
  [0.88386192 0.83135504 0.45648524 0.67404836 0.02629976]]

 [[0.82767627 0.71750067 0.6204231  0.65560017 0.85805017]
  [0.77819448 0.10582216 0.74351418 0.94061952 0.66886768]
  [0.91704796 0.99771761 0.17093004 0.14740682 0.95234177]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [8]:
b = np.ones((5, 2, 3))


### 6. Print b.


In [9]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [10]:
print(a.size == b.size)

True



### 8. Are you able to add a and b? Why or why not?


In [11]:
#Two arrays can be added only if their shapes are compatible, in this case they are not the same shape so it is not possible to add them toghether. 
a + b 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [18]:
c = b.transpose(1, 2, 0)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [19]:
d = a + c

#Both arrays have the same size.

array([[[1.67092717, 1.97148054, 1.30944829, 1.92458055, 1.03261588],
        [1.74698709, 1.85811075, 1.16735022, 1.63663272, 1.63236285],
        [1.88386192, 1.83135504, 1.45648524, 1.67404836, 1.02629976]],

       [[1.82767627, 1.71750067, 1.6204231 , 1.65560017, 1.85805017],
        [1.77819448, 1.10582216, 1.74351418, 1.94061952, 1.66886768],
        [1.91704796, 1.99771761, 1.17093004, 1.14740682, 1.95234177]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [28]:
print(a)
print(" ")
print(d)

# a is the original array and d is has the same vales plus 1 as a result of adding a to a matrix of ones. 

[[[0.67092717 0.97148054 0.30944829 0.92458055 0.03261588]
  [0.74698709 0.85811075 0.16735022 0.63663272 0.63236285]
  [0.88386192 0.83135504 0.45648524 0.67404836 0.02629976]]

 [[0.82767627 0.71750067 0.6204231  0.65560017 0.85805017]
  [0.77819448 0.10582216 0.74351418 0.94061952 0.66886768]
  [0.91704796 0.99771761 0.17093004 0.14740682 0.95234177]]]
 
[[[1.67092717 1.97148054 1.30944829 1.92458055 1.03261588]
  [1.74698709 1.85811075 1.16735022 1.63663272 1.63236285]
  [1.88386192 1.83135504 1.45648524 1.67404836 1.02629976]]

 [[1.82767627 1.71750067 1.6204231  1.65560017 1.85805017]
  [1.77819448 1.10582216 1.74351418 1.94061952 1.66886768]
  [1.91704796 1.99771761 1.17093004 1.14740682 1.95234177]]]



### 12. Multiply a and c. Assign the result to e.


In [24]:
e = a * c
print (e)

[[[0.67092717 0.97148054 0.30944829 0.92458055 0.03261588]
  [0.74698709 0.85811075 0.16735022 0.63663272 0.63236285]
  [0.88386192 0.83135504 0.45648524 0.67404836 0.02629976]]

 [[0.82767627 0.71750067 0.6204231  0.65560017 0.85805017]
  [0.77819448 0.10582216 0.74351418 0.94061952 0.66886768]
  [0.91704796 0.99771761 0.17093004 0.14740682 0.95234177]]]




### 13. Does e equal to a? Why or why not?


In [25]:
print(e == a)
# all the values are the same, meaning the matrix are equal. This is true as e is the result or multiplying a to a matrix of ones, this will give the same results. 

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [27]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print (f"d_max is: {d_max}")
print (f"d_min is: {d_min}")
print (f"d_mean is: {d_mean}")

d_max is: 1.9977176111910309
d_min is: 1.02629975534605
d_mean is: 1.6308086323586706



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [31]:
f = np.empty((2, 3, 5))




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [39]:
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[(d == d_mean)] = 50
f[(d == d_min)] = 0
f[(d == d_max)] = 100





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [38]:
print(d)
print(f)  

[[[1.67092717 1.97148054 1.30944829 1.92458055 1.03261588]
  [1.74698709 1.85811075 1.16735022 1.63663272 1.63236285]
  [1.88386192 1.83135504 1.45648524 1.67404836 1.02629976]]

 [[1.82767627 1.71750067 1.6204231  1.65560017 1.85805017]
  [1.77819448 1.10582216 1.74351418 1.94061952 1.66886768]
  [1.91704796 1.99771761 1.17093004 1.14740682 1.95234177]]]
[[[ 75.  75.  25.  75.  25.]
  [ 75.  75.  25.  75.  75.]
  [ 75.  75.  25.  75.   0.]]

 [[ 75.  75.  25.  75.  75.]
  [ 75.  25.  75.  75.  75.]
  [ 75. 100.  25.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [42]:
f = np.empty((2, 3, 5), dtype='U1')
f[(d > d_min) & (d < d_mean)] = 'A'
f[(d > d_mean) & (d < d_max)] = 'B'
f[(d == d_mean)] = 'C'
f[(d == d_min)] = 'D'
f[(d == d_max)] = 'E'
print(f)  

[[['B' 'B' 'A' 'B' 'A']
  ['B' 'B' 'A' 'B' 'B']
  ['B' 'B' 'A' 'B' 'D']]

 [['B' 'B' 'A' 'B' 'B']
  ['B' 'A' 'B' 'B' 'B']
  ['B' 'E' 'A' 'A' 'B']]]
